---
- hosts: all
  become: yes
  gather_facts: True
  vars:
    user: "{{ ansible_facts['env']['SUDO_USER'] or ansible_facts['user_id'] }}"
  roles:
    - { role: server, zsh_user: "{{ user }}", tags: dotfiles }
    - { role: terraform, username: "{{ user }}", tags: virtools }