- hosts: all
  become: yes
  become_user: root
  gather_facts: True
  vars:
    user: "{{ ansible_user_id }}"
  roles:
    - { role: server, zsh_user: "{{ user }}", tags: dotfiles }
    - { role: terraform, username: "{{ user }}", tags: virtools }
