---
dependency:
  name: galaxy
driver:
  name: podman
  options:
    network: bridge
    dns:
      - 8.8.8.8
      - 8.8.4.4
    timeout: 7200
    force_destroy: true
    remove_volumes: true
    force_remove: true
    destroy_command: podman rm -f -t 0 {{ item.name }}
    image: fedora:latest
    pre_build_image: true
    privileged: true
    command: sleep infinity
provisioner:
  name: ansible
  timeout:
    prepare: 3600
    create: 1800
    converge: 7200
    destroy: 7200
  inventory:
    group_vars:
      all: {}
    host_vars:
      fedora-newest:
        ansible_python_interpreter: /usr/bin/python3
        fonts: []
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
scenario:
  name: full
  test_sequence:
    - dependency
    - destroy
    - create
    - prepare
    - converge
    - verify
    - destroy