---
packages_redhat:
  - qemu-kvm
  - libvirt
  - libvirt-devel
  - virt-install
  - libvirt-devel
  - libxml2-devel
  - make
  - ruby-devel
  - libxslt-devel
  - libguestfs-tools-c
  - byacc
  - gcc
  - gcc-c++
  - cmake
  - git
