---
neovim_arch_map:
  x86_64: nvim-linux-x86_64
  aarch64: nvim-linux-arm64
neovim_arch: "{{ neovim_arch_map[ansible_architecture] }}"
neovim_tarball_url: "https://github.com/neovim/neovim/releases/latest/download/{{ neovim_arch }}.tar.gz"
neovim_pip_package: neovim