---
packages_rpm:
  - zsh
  - acl
  - git
  - curl
  - gcc
  - gcc-c++
  - cmake
  - golang
  - fuse3
  - nodejs22
  - python3
  - python3-pip
  - python3-setuptools
  - python3-devel
  - python3-neovim
  - unzip
  - fontconfig-devel
  - alacritty