ARG BASE_IMAGE
FROM ${BASE_IMAGE}

RUN zypper --non-interactive install \
        python3 \
        python311 \
        python311-rpm \
        python3-rpm \
        sudo \
        curl \
        tar \
    && zypper clean --all