---
username: "{{ ansible_facts['user_id'] }}"
user_groups:
  - libvirt
  - vagrant

sudoers: |
  Cmnd_Alias VAGRANT_NFS = /bin/mount, /bin/umount, /sbin/mount.nfs, /sbin/umount.nfs
  %vagrant ALL=(root) NOPASSWD: VAGRANT_NFS
