---
- name: Add official HashiCorp RPM Repository
  ansible.builtin.yum_repository:
    name: hashicorp
    description: HashiCorp Stable - $basearch
    baseurl: "https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable"
    enabled: true
    gpgcheck: true
    gpgkey: https://rpm.releases.hashicorp.com/gpg
  when: 
    - ansible_facts['os_family'] == 'RedHat'
    - ansible_facts['distribution'] != 'Fedora'

# Add HashiCorp GPG Key for Debian/Ubuntu
- name: Download HashiCorp GPG key
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /etc/apt/keyrings/hashicorp-archive-keyring.asc
    mode: '0644'
  when: ansible_facts['os_family'] == 'Debian'

# Add HashiCorp apt repository for Debian/Ubuntu
- name: Add HashiCorp apt repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/hashicorp-archive-keyring.asc] https://apt.releases.hashicorp.com {{ ansible_facts['distribution_release'] }} main"
    state: present
  when: ansible_facts['os_family'] == 'Debian'

# Install Vagrant package across all supported platforms
- name: Install Vagrant
  ansible.builtin.package:
    name: vagrant
    state: present
