---

- name: Install hashicorp repo key on Debian
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present
  when: ansible_facts['os_family'] == 'Debian'

- name: Install hashicorp repo on RedHat
  shell: dnf config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
  when: ansible_os_family == 'RedHat' and ansible_distribution != 'Fedora'

- name: Install hashicorp repo on Fedora
  shell: dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
  when: ansible_facts['distribution'] == 'Fedora'

# zypper addrepo https://download.opensuse.org/repositories/systemsmanagement:terraform/openSUSE_Tumbleweed/systemsmanagement:terraform.repo
# zypper addrepo https://download.opensuse.org/repositories/systemsmanagement:terraform/15.6/systemsmanagement:terraform.repo

# - name: Add python development repository
#   community.general.zypper_repository:
#     "https://download.opensuse.org/repositories/systemsmanagement:terraform/{{ansible_distribution_major_version}}/systemsmanagement:terraform.repo"
#   when: ansible_distribution == "openSUSE Tumbleweed"

- name: Install hashicorp apt repo on Debian
  apt_repository:
    repo: deb https://apt.releases.hashicorp.com {{ansible_lsb['codename']}} main
    state: present
  when: ansible_facts['os_family'] == 'Debian'
