---

- name: Load terraform packages redhat variable file
  include_vars: packages_redhat.yml

- name: Load terraform packages debian variable file
  include_vars: packages_debian.yml

- name: Enable the powertools/crb repo so devel packages are available
  community.general.dnf_config_manager:
    name: "{{ 'powertools' if (ansible_facts['distribution'] == 'CentOS' and ansible_facts['distribution_major_version'] == '8') else 'crb' }}"
    state: enabled
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution'] != 'Fedora'

- name: Install @virtualization group on RedHats
  dnf:
    name: "{{ packages_redhat }}"
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Install deps on Debians
  apt:
    name: "{{ packages_debian }}"
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == 'Debian'

- name: Enable source repos on Debains
  replace:
    path: /etc/apt/sources.list
    regexp: '# deb-src '
    replace: 'deb-src '
  when: ansible_facts['os_family'] == 'Debian'
