---

- name: adding existing user '{{ username }}' to group sudo
  user:
    name: '{{ username }}'
    groups: libvirt
    append: yes

- name: Install terraform
  package:
    name: 
      - terraform 
      - packer 
      - vagrant
    state: latest

