---

- name: Build-deps on Debians for vagrant-libvirt
  apt:
    name:
     - vagrant
     - ruby-libvirt
    state: build-dep
    update_cache: yes
  when: ansible_facts['os_family'] == 'Debian'

- name: Install libssh sources on Fedora
  shell: >
    mkdir -p /tmp/libssh && cd /tmp/libssh && rm -rf ./* && \
    dnf download --source libssh && \ 
    rpm2cpio libssh-*.src.rpm | cpio -imdV && \
    tar xf libssh-*.tar.xz && \
    mkdir build && pushd build && \
    cmake ../libssh-*/ -DOPENSSL_ROOT_DIR=/opt/vagrant/embedded/ && make && \
    sudo /usr/bin/cp -a lib/libssh* /opt/vagrant/embedded/lib && \
    rm -rf /tmp/libssh
  when: ansible_os_family == 'RedHat' and ansible_distribution != 'Fedora'
  become: yes

- name: Install krb5-libs sources on Fedora
  shell: >
    mkdir -p /tmp/krb5-libs && cd /tmp/krb5-libs && rm -rf ./* && \
    dnf download --source krb5-libs && \
    rpm2cpio krb5-*.src.rpm | cpio -imdV && \
    tar xf krb5-*.tar.gz && \
    cd krb5-*/src && \
    ./configure && make && \
    sudo /usr/bin/cp -a lib/crypto/libk5crypto.* /opt/vagrant/embedded/lib/ && \
    rm -rf /tmp/krb5-libs
  when: ansible_os_family == 'RedHat' and ansible_distribution != 'Fedora'
  become: yes



- name: Insert sudoers config for NFS
  ansible.builtin.blockinfile:
    block:  "{{ sudoers }}"
    path: /etc/sudoers.d/vagrant-nfs
    backup: yes
    create: yes
    validate: visudo -cf %s

- name: Ensure group "{{ item }}" exists
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop: "{{ user_groups }}"

- name: adding existing user '{{ username }}' to group {{ item }}
  user:
    name: '{{ username }}'
    groups: "{{ item }}"
    append: yes
  loop: "{{ user_groups }}"

- name: ensure libvirtd service is enabled and active
  service:
    name: libvirtd
    enabled: yes
    state: started

- name: Install vagrant-libvirt
  shell: vagrant plugin install vagrant-libvirt
  become: yes
  become_user: "{{ username }}"

