---

- name: dotfiles git clone for {{ zsh_user }}
  git:
    repo: https://github.com/janekzieleznicki/dotfiles.git
    dest: /home/{{ zsh_user }}/.dotfiles
    force: yes
  become: yes
  become_user: "{{ zsh_user }}"
  vars:
    allow_world_readable_tmpfiles: true

- name: dotfiles install for {{ zsh_user }}
  command: /home/{{ zsh_user }}/.dotfiles/install
  become: yes
  become_user: "{{ zsh_user }}"

- name: change user shell to zsh
  become: yes
  user:
    name: "{{ zsh_user }}"
    shell: /bin/zsh

- name: nvim plug install
  command: nvim --headless +PlugInstall +qall
  become: yes
  become_user: "{{ zsh_user }}"

- name: Rustup install
  shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  args:
    warn: no
  become: yes
  become_user: "{{ zsh_user }}"
