---
- name: Distro debug
  debug: "msg='Detected os_family: {{ ansible_os_family }} and distribution: {{ ansible_distribution }} version: {{ ansible_distribution_major_version }}'"

- name: Ensure the crb repository is enabled
  community.general.dnf_config_manager:
    name: crb
    state: enabled
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version >= 9

- name: Ensure the crb repository is enabled
  community.general.dnf_config_manager:
    name: powertools
    state: enabled
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version == 8

- name: install the epel repo
  dnf:
    name: epel-release
    state: present
    disable_gpg_check: yes
  when: ansible_facts['distribution'] == "CentOS" or ansible_facts['distribution'] == "RedHat"

- name: Install packages rpm
  package:
    name:
      [
        zsh,
        acl,
        git,
        curl,
        gcc,
        gcc-c++,
        go,
        fuse,
        nodejs,
        python3,
        python3-pip,
        python3-setuptools,
        python3-devel,
        unzip,
      ]
    state: latest
  when: ansible_facts['os_family'] == "RedHat" or ansible_facts['os_family'] == "Suse"

- name: Install packages apt
  apt:
    name:
      [
        zsh,
        acl,
        git,
        curl,
        fuse,
        nodejs,
        python3,
        python3-pip,
        python3-setuptools,
        python3-neovim,
        unzip,
      ]
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Install packages swupd
  swupd:
    name: "c-basic zsh git acl curl fuse nodejs-basic python3-basic unzip"
    state: present
  when: ansible_facts['os_family'] == 'ClearLinux'

- name: Install neovim python package
  pip:
    name: neovim
    executable: pip3
  when: ansible_facts['distribution'] == "CentOS" or ansible_facts['distribution'] == 'ClearLinux'

- name: Install python3-neovim package by package manager
  package:
    name:
      - python3-neovim
    state: latest
  when: ansible_facts['distribution'] == "Fedora" or ansible_facts['os_family'] == "Suse"

- file:
    path: /home/{{ zsh_user }}/.local/bin
    state: directory
  become: true
  become_user: "{{ zsh_user }}"

- name: Download neovim appimage on CentOS
  get_url:
    url: https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
    dest: /home/{{ zsh_user }}/.local/bin/nvim.appimage
    mode: "0755"
  become: true
  become_user: "{{ zsh_user }}"

- name: Install fonts
  with_items:
    - "Hack"
    - "JetBrainsMono"
  include_role:
    name: nerd-font
  vars:
    font: "{{ item }}"
