---
- name: Load server packages rpm variable file
  include_vars: packages_rpm.yml

- name: Load server packages apt variable file
  include_vars: packages_apt.yml

- name: Load server neovim variable file
  include_vars: neovim.yml

- name: Load server fonts variable file
  include_vars: fonts.yml

- name: Distro debug
  debug: "msg='Detected os_family: {{ ansible_facts['os_family'] }} and distribution: {{ ansible_facts['distribution'] }} version: {{ ansible_facts['distribution_major_version'] }}'"

- name: Install dnf-plugins-core for RedHat family
  dnf:
    name: dnf-plugins-core
    state: present
  ignore_errors: yes
  when: ansible_facts['os_family'] == "RedHat"

- name: Enable CRB / Powertools repository for devel packages
  block:
    - name: Enable CodeReady Builder on Red Hat Enterprise Linux
      ansible.builtin.command: subscription-manager repos --enable "codeready-builder-for-rhel-{{ ansible_distribution_major_version }}-{{ ansible_architecture }}-rpms"
      when: ansible_distribution == "RedHat"
      register: rhel_crb
      changed_when: "'enabled' in rhel_crb.stdout"

    - name: Enable CodeReady Builder on Oracle Linux
      ansible.builtin.command: dnf config-manager --set-enabled "ol{{ ansible_distribution_major_version }}_codeready_builder"
      when: ansible_distribution == "OracleLinux"
      register: oracle_crb
      changed_when: oracle_crb.rc == 0

    - name: Enable CRB / Powertools on CentOS, Rocky, or AlmaLinux
      ansible.builtin.command: "dnf config-manager --set-enabled {{ 'crb' if ansible_distribution_major_version | int >= 9 else 'powertools' }}"
      when: ansible_distribution in ["CentOS", "Rocky", "AlmaLinux"]
      register: clone_crb
      changed_when: clone_crb.rc == 0
  when: ansible_os_family == "RedHat"

- name: Install EPEL repository for RHEL derivatives (skip Fedora and OracleLinux)
  ansible.builtin.dnf:
    name: epel-release
    state: present
    disable_gpg_check: yes
  when:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution'] not in ["Fedora", "Fedora Linux", "OracleLinux"]
- name: Install packages rpm
  package:
    name: "{{ packages_rpm }}"
    state: latest
  ignore_errors: yes
  when: ansible_facts['os_family'] == "RedHat"
- name: Install apt-utils for Debian family
  apt:
    name: apt-utils
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Install packages apt
  apt:
    name: "{{ packages_apt }}"
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Install neovim python package
  pip:
    name: "{{ neovim_pip_package }}"
    executable: pip3
  when: ansible_facts['distribution'] == "CentOS"

- name: Install python3-neovim package by package manager
  package:
    name:
      - python3-neovim
    state: latest
  ignore_errors: yes
  when: ansible_facts['distribution'] == "Fedora" or ansible_facts['os_family'] == "Suse"

- name: Ensure bin directory exists for zsh_user
  file:
    path: /home/{{ zsh_user }}/.local/bin
    state: directory
  become: no
  become_user: "{{ zsh_user }}"



- name: Download neovim appimage
  get_url:
    url: "{{ neovim_appimage_url }}"
    dest: /home/{{ zsh_user }}/.local/bin/nvim.appimage
    mode: "0755"
  ignore_errors: yes
  become: no

- name: Install fonts
  loop: "{{ fonts }}"
  include_role:
    name: nerd-font
  vars:
    font: "{{ item }}"
  ignore_errors: yes