---

- name: install the epel repo
  dnf:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    state: present
    disable_gpg_check: yes
  when: ansible_facts['distribution'] == "CentOS"

- name: Install packages rpm
  package:
    name: [zsh, acl, git, curl, neovim, nodejs, python3, python3-pip, python3-setuptools]
    state: latest
  when: ansible_facts['os_family'] == "RedHat" or ansible_facts['os_family'] == "Suse"

- name: Install packages apt
  apt:
    name: [zsh, acl, git, curl, neovim, nodejs, python3, python3-pip, python3-setuptools, python3-neovim]
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Install packages swupd
  swupd:
    name: 'zsh git acl curl neovim nodejs-basic python3-basic'
    state: present
  when: ansible_facts['os_family'] == 'ClearLinux'

- name: Distro debug
  debug: "msg='Detected os_family: {{ ansible_facts['os_family'] }} and distribution: {{ ansible_facts['distribution'] }}'"

- name: Install neovim python package
  pip:
    name: neovim
    executable: pip3
  when: ansible_facts['distribution'] == "CentOS" or ansible_facts['distribution'] == 'ClearLinux'

- name: Install python3-neovim package by package manager
  package:
    name:
      - python3-neovim
    state: latest
  when: ansible_facts['distribution'] == "Fedora" or ansible_facts['os_family'] == "Suse" 

- file:
    path: /home/{{ zsh_user }}/.local/bin
    state: directory
  become: yes
  become_user: "{{ zsh_user }}"
  when: ansible_facts['distribution'] == "CentOS"

- name: Download neovim appimage on CentOS
  get_url: 
    url: https://github.com/neovim/neovim/releases/download/v0.6.0/nvim.appimage
    dest: /home/{{ zsh_user }}/.local/bin/nvim.appimage
    mode: '0755'
  become: yes
  become_user: "{{ zsh_user }}"
  when: ansible_facts['distribution'] == "CentOS"
