---
- name: Load server packages rpm variable file
  include_vars: packages_rpm.yml

- name: Load server packages apt variable file
  include_vars: packages_apt.yml

- name: Load server neovim variable file
  include_vars: neovim.yml

- name: Load server fonts variable file
  include_vars: fonts.yml

- name: Distro debug
  debug: "msg='Detected os_family: {{ ansible_facts['os_family'] }} and distribution: {{ ansible_facts['distribution'] }} version: {{ ansible_facts['distribution_major_version'] }}'"

- name: Enable the powertools/crb repo so packages are available
  community.general.dnf_config_manager:
    name: "{{ 'powertools' if (ansible_facts['distribution'] == 'CentOS' and ansible_facts['distribution_major_version'] == '8') else 'crb' }}"
    state: enabled
  when: ansible_facts['os_family'] == "RedHat"

- name: Install the epel repo
  dnf:
    name: epel-release
    state: present
    disable_gpg_check: yes
  when: ansible_facts['distribution'] == "CentOS" or ansible_facts['distribution'] == "RedHat"

- name: Install packages rpm
  package:
    name: "{{ packages_rpm }}"
    state: latest
  when: ansible_facts['os_family'] == "RedHat" or ansible_facts['os_family'] == "Suse"

- name: Install packages apt
  apt:
    name: "{{ packages_apt }}"
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Install neovim python package
  pip:
    name: "{{ neovim_pip_package }}"
    executable: pip3
  when: ansible_facts['distribution'] == "CentOS" or ansible_facts['distribution'] == 'ClearLinux'

- name: Install python3-neovim package by package manager
  package:
    name:
      - python3-neovim
    state: latest
  when: ansible_facts['distribution'] == "Fedora" or ansible_facts['os_family'] == "Suse"

- file:
    path: /home/{{ zsh_user }}/.local/bin
    state: directory
  become: true
  become_user: "{{ zsh_user }}"

- name: Download neovim appimage
  get_url:
    url: "{{ neovim_appimage_url }}"
    dest: /home/{{ zsh_user }}/.local/bin/nvim.appimage
    mode: "0755"
  become: true
  become_user: "{{ zsh_user }}"

- name: Install fonts
  with_items: "{{ fonts }}"
  include_role:
    name: nerd-font
  vars:
    font: "{{ item }}"
