---
dependency:
  name: galaxy
driver:
  name: containers
platforms:
  - name: fedora-newest
    image: localhost/molecule-fedora:41
    pre_build_image: true
  - name: fedora-previous
    image: localhost/molecule-fedora:40
    pre_build_image: true
  - name: rhel8
    image: localhost/molecule-el:8
    pre_build_image: true
  - name: centos-stream
    image: localhost/molecule-el:stream9
    pre_build_image: true
  - name: rocky
    image: localhost/molecule-el:rocky-9
    pre_build_image: true
  - name: alma
    image: localhost/molecule-el:alma-9
    pre_build_image: true
  - name: oracle
    image: localhost/molecule-el:oracle-9
    pre_build_image: true
  - name: opensuse
    image: localhost/molecule-suse:tumbleweed
    pre_build_image: true
  - name: opensuse-leap
    image: localhost/molecule-suse:leap-15.6
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    host_vars:
      rhel8:
        ansible_python_interpreter: /usr/bin/python3.11
      opensuse-leap:
        ansible_python_interpreter: /usr/bin/python3.11
  playbooks:
    prepare: prepare.yml
scenario:
  name: smoke
  test_sequence:
    - dependency
    - destroy
    - create
    - prepare
    - verify
verifier:
  name: ansible
