---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: fedora-newest
    image: quay.io/fedora/fedora-bootc:latest
    pre_build_image: true
    privileged: true
    command: /sbin/init

  - name: rhel8
    image: quay.io/rockylinux/rockylinux:8
    pre_build_image: true
    privileged: true

  - name: rocky
    image: quay.io/rockylinux/rockylinux:9
    pre_build_image: true
    privileged: true

  - name: alma
    image: quay.io/almalinux/almalinux:9
    pre_build_image: true
    privileged: true

  - name: rocky-10
    image: quay.io/rockylinux/rockylinux:10
    pre_build_image: true
    privileged: true

  - name: oracle-10
    image: container-registry.oracle.com/os/oraclelinux:10
    pre_build_image: true
    privileged: true

  - name: opensuse
    image: registry.opensuse.org/opensuse/tumbleweed:latest
    pre_build_image: true
    privileged: true

  - name: opensuse-leap
    image: registry.opensuse.org/opensuse/leap:latest
    pre_build_image: true
    privileged: true

  - name: debian-trixie
    image: debian:trixie
    pre_build_image: true
    privileged: true
  - name: ubuntu-24.04
    image: ubuntu:24.04
    pre_build_image: true
    privileged: true
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
  inventory:
    host_vars:
      rhel8:
        ansible_python_interpreter: /usr/bin/python3.11
      opensuse-leap:
        ansible_python_interpreter: /usr/bin/python3
      debian-trixie:
        ansible_python_interpreter: /usr/bin/python3
      ubuntu-24.04:
        ansible_python_interpreter: /usr/bin/python3

scenario:
  name: smoke
  test_sequence:
    - dependency
    - destroy
    - create
    - prepare
    - verify

verifier:
  name: ansible