---
dependency:
  name: galaxy
driver:
  name: containers
platforms:
 - name: fedora-newest
   image: fedora:latest
   pre_build_image: true

 - name: rhel8
   image: rockylinux:8
   pre_build_image: true

 - name: rocky
   image: rockylinux:9
   pre_build_image: true

 - name: alma
   image: almalinux:latest
   pre_build_image: true

 - name: rocky-10
   image: rockylinux:10
   pre_build_image: true

 - name: oracle-10
   image: oraclelinux:10
   pre_build_image: true

 - name: opensuse
   image: opensuse/tumbleweed:latest
   pre_build_image: true

 - name: opensuse-leap
   image: opensuse/leap:latest
   pre_build_image: true
provisioner:
  name: ansible
  inventory:
    host_vars:
      rhel8:
        ansible_python_interpreter: /usr/bin/python3.11
      opensuse-leap:
        ansible_python_interpreter: /usr/bin/python3.11
  playbooks:
    prepare: prepare.yml
scenario:
  name: smoke
  test_sequence:
    - dependency
    - destroy
    - create
    - prepare
    - verify
verifier:
  name: ansible
