- name: Loop over nerd fonts to ensure each is installed
  ansible.builtin.include_tasks: nerd_font_font.yml
  loop: '{{ nerd_fonts }}'
  loop_control:
    loop_var: font
  when: nerd_fonts | default([]) | length > 0
- name: Ensure fonts directory exists (Darwin only)
  ansible.builtin.file:
    path: '{{ user_home }}/.local/share/fonts'
    state: directory
    mode: '0755'
  become: true
  become_user: '{{ username }}'
  when: (ansible_facts['os_family'] | default('')) == 'Darwin'
