---
galaxy_info:
  author: janekzieleznicki
  description: "Install Nerd Fonts."
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions: ["8", "9", "10"]
    - name: Fedora
      versions: [all]
    - name: Debian
      versions: [trixie]
    - name: Ubuntu
      versions: [noble]
    - name: opensuse
      versions: [all]
dependencies: []
